`Q1` **Arrays**

In [2]:
import numpy as np

def arrays(arr):
    return(np.array(arr[::-1], float))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


`Q2` **Shape and Reshape**

In [10]:
#change_array = np.array([1,2,3,4,5,6])
#change_array.shape = (3, 2)
#print (change_array)  

In [11]:
#my_array = np.array([1,2,3,4,5,6])
#print (np.reshape(my_array,(3,2)))


In [9]:
print(np.array(input().split(), int).reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


`Q3` **Transpose and Flatten**

In [23]:
n, m = map(int, input().split())

Trans_flat = np.array([input().strip().split() for _ in range(n)], int)
print (Trans_flat.transpose())
print (Trans_flat.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


`Q4` **Concatenate** 

In [25]:
P, N, M = map(int, input().split())
A = np.array([input().split() for _ in range (P)], int)
B = np.array([input().split() for _ in range(N)], int)
print(np.concatenate((A,B), axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


`Q5` **Zeros and Ones**

In [26]:
N = tuple(map(int, input().split()))
print(np.zeros(N, int))
print(np.ones(N, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


`Q 6` **Eye and Identity**

In [28]:
np.set_printoptions(sign=' ')
print(np.eye(*map(int, input().split())))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


`Q 7` **Array Mathematics**

In [32]:
N, M = map(int, input().split())
A = np.array([list(map(int, input().split())) for n in range (N)])
B = np.array([list(map(int, input().split())) for n in range (N)])

print(A+B)
print(A-B)
print(A*B)
print(A//B)
print(A%B)
print(A**B)

1 4 
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


`Q 8` **Floor, Ceil and Rint**

In [34]:
arr = np.array(input().split(), float)

np.set_printoptions(sign=' ')

print(np.floor(arr))
print(np.ceil(arr))
print(np.rint(arr))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


`Q 9`**Sum and Prod**

In [38]:


#my_array = np.array([ [1, 2], [3, 4] ])

#print (np.prod(my_array, axis = 0))            #Output : [3 8]
#print (np.prod(my_array, axis = 1))            #Output : [ 2 12]
#print (np.prod(my_array, axis = None))         #Output : 24
#print (np.prod(my_array))                      #Output : 24

In [41]:
N, M = map(int, input().split())

A = np.array([input().split() for _ in range(N)], int)
print(np.prod(np.sum(A, axis = 0), axis = 0))

2 2
1 2
3 4
24


`Q 10` **Min and Max**

In [46]:
N, M = map(int, input().split())

A = np.array([input().split() for _ in range(N)], int)
print(np.max(np.min(A, axis = 1), axis = 0))

4 2
2 5
3 7
1 3
4 0
3


`Q11` **Mean, Var, and Std**

In [49]:
N, M = map(int, input().split())

empty_list = []
for i in range(N):
    A = list(map(int, input().split()))
    empty_list.append(A)
    
l = np.array(empty_list)

np.set_printoptions(legacy = '1.13')
print(np.mean(l, axis=1))
print(np.var(l, axis = 0))
print(np.std(l))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


`Q 12` **Dot and Cross**

In [54]:
n = int(input())
a = np.array([input().split() for _ in range(n)], int)
b = np.array([input().split() for _ in range(n)], int)
print(np.dot(a, b))    

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


`Q 13` **Inner and Outer**

In [2]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


` Q 14`**Polynomials**

In [3]:
pol = [float(x) for x in input().split()]
x = float(input())

print(np.polyval(pol, x))

1.1 2 3
0
3.0


`Q 15` **Linear Algebra**

In [4]:
N = int(input())
A = np.array([input().split() for _ in range(N)], float)
print(round(np.linalg.det(A),2))

2
1.1 1.1
1.1 1.1
0.0
